### ISSUE TITLE
Mentions tab displays inaccurate number

### ISSUE THREAD

**Issue by frozenpandaman** [Rotonde/rotonde-client#88]
![image](https://user-images.githubusercontent.com/7245874/32411771-eec260a2-c1a0-11e7-843d-d0bf845fdcda.png)

number can also be higher (e.g. displays **4 Mentions** but 10 are shown in the list)

**Comment by hermes-diactoros** [comment]
Can you post the Rotonde URL of that particular site? We've just rolled out multiple mention support and some parts need fixing.

**Comment by frozenpandaman** [comment]
Sure, here you go: dat://9984032be16f48fcc9fab3e7a885fcdcd0b188a9e3e31aaf0c9c43995745455d/

@neauoire's (dat://2f21e3c122ef0f2555d3a99497710cd875c7b0383f998a2d37c02c042d598485/#mentions) also says **4 Mentions** on the tab bar but displays 9 at the moment.

**Comment by eelfroth** [comment]
this is fixed in #95 
issue can be closed

**Comment by frozenpandaman** [comment]
@eelfroth @cblgh Still happening for me on 0.1.67.

Shows 12 mentions but only 3 in list.

![image](https://user-images.githubusercontent.com/7245874/32423710-e5893ee0-c25c-11e7-874c-d9021bbb371e.png)

**Comment by frozenpandaman** [comment]
Another example on @_discovery's page (dat://7fa4dea2b16585f994f576cc1356dc6443b8449b00fbadf70cb19827d2238fd3/#mentions)

![image](https://user-images.githubusercontent.com/7245874/32423752-338fe738-c25d-11e7-959f-e1f76e20ddb2.png)

**Comment by eelfroth** [comment]
whaaat, I was so sure this works now!
maybe it's whispers misbehaving in some way…

**Comment by eelfroth** [comment]
@frozenpandaman did #98 fix it?

**Comment by frozenpandaman** [comment]
@eelfroth Sorry for the late reply – just confirming that everything seems to be working now. :)

**Comment by eelfroth** [comment]
yeah, finally works now :)
